import { createAnimationTracksFromLegacyLayer } from './layerAnimation';
import { createFieldDefinition, createLayerOfKind, createLayerSemantics } from './factory';
import { createId } from './id';
import {
  assertStaggerFits,
  buildLayerMotionKeyframes,
  type MotionDirection,
  type MotionStyle,
} from './motionPresets';
import {
  applyStylePack,
  resolveStylePackMotion,
  STYLE_TOKEN_KEYS,
  styleTokenValue,
  type StylePackId,
} from './stylePacks';
import type { Composition, EasingPreset, Layer, LayerTransform, Paint } from './types';

export interface LowerThirdRecipeOptions {
  name?: string;
  stylePack?: StylePackId;
  placement?: Partial<Pick<LayerTransform, 'x' | 'y' | 'width' | 'height'>>;
  content?: { headline?: string; subheadline?: string };
  fieldKeys?: { headline?: string; subheadline?: string };
  theme?: {
    background?: Paint;
    accent?: Paint;
    primaryText?: string;
    secondaryText?: string;
  };
  motion?: {
    style?: MotionStyle;
    entrance?: MotionDirection;
    exit?: MotionDirection;
    staggerFrames?: number;
    entranceDurationFrames?: number;
    exitDurationFrames?: number;
    entranceEasing?: EasingPreset;
    exitEasing?: EasingPreset;
  };
}

type ResolvedLowerThirdMotion = Required<NonNullable<LowerThirdRecipeOptions['motion']>>;

export interface MaterializedLowerThird {
  recipe: 'lower-third';
  name: string;
  stylePack?: StylePackId;
  groupId: string;
  timelineGroupId: string;
  layers: {
    panel: string;
    accent: string;
    headline: string;
    subheadline: string;
  };
  fields: { headline: string; subheadline: string };
}

function uniqueFieldKey(composition: Composition, requested: string, fallback: string): string {
  const base = (requested.trim() || fallback).replace(/[^A-Za-z0-9_]+/g, '_').replace(/^\d/, '_$&');
  let key = base || fallback;
  let suffix = 2;
  while (composition.dataFields.some((field) => field.key === key)) key = `${base}_${suffix++}`;
  return key;
}

function recipeLayer(
  composition: Composition,
  kind: 'rectangle' | 'text',
  name: string,
  groupId: string,
  role: Layer['semantics']['role'],
  tags: string[],
  onAir: LayerTransform,
  motion: ResolvedLowerThirdMotion,
  cascadeIndex: number,
  isRevealMask = false,
): Layer {
  const layer = createLayerOfKind(kind);
  layer.name = name;
  layer.groupId = groupId;
  layer.semantics = createLayerSemantics({
    role,
    tags: ['lower-third', ...tags],
    description: `${role} generated by the lower-third authoring recipe.`,
  });

  layer.keyframes = buildLayerMotionKeyframes({
    composition,
    onAir,
    style: motion.style,
    entrance: motion.entrance,
    exit: motion.exit,
    staggerFrames: motion.staggerFrames,
    cascadeIndex,
    cascadeCount: 4,
    isRevealMask,
    entranceDurationFrames: motion.entranceDurationFrames,
    exitDurationFrames: motion.exitDurationFrames,
    entranceEasing: motion.entranceEasing,
    exitEasing: motion.exitEasing,
  });
  layer.animationTracks = createAnimationTracksFromLegacyLayer(layer);
  return layer;
}

/**
 * Materialize a semantic lower third into ordinary portable OGraf layers and fields. The recipe
 * leaves no runtime dependency: every output remains editable through normal layer operations.
 */
export function materializeLowerThird(
  composition: Composition,
  options: LowerThirdRecipeOptions = {},
): MaterializedLowerThird {
  if (!composition.keyframes.some((keyframe) => keyframe.role === 'step')) {
    throw new Error('The lower-third recipe requires at least one pausable OGraf Step.');
  }

  const name = options.name?.trim() || 'Lower Third';
  const stylePack = options.stylePack;
  if (stylePack) {
    applyStylePack(composition, stylePack, { refreshTokens: true });
  }
  const packMotion = stylePack ? resolveStylePackMotion(composition, stylePack) : null;
  const packValue = (key: Parameters<typeof styleTokenValue>[1], fallback: string | number) =>
    stylePack ? styleTokenValue(composition, key, fallback) : fallback;
  const x = Math.round(options.placement?.x ?? composition.width * 0.08);
  const y = Math.round(options.placement?.y ?? composition.height * 0.74);
  const width = Math.max(320, Math.round(options.placement?.width ?? composition.width * 0.62));
  const height = Math.max(96, Math.round(options.placement?.height ?? composition.height * 0.16));
  const accentWidth = Math.max(8, Math.round(height * 0.08));
  const horizontalPadding = Math.max(24, Math.round(height * 0.22));
  const groupId = createId('group');
  const timelineGroupId = createId('timeline-group');
  const motion = {
    style: options.motion?.style ?? 'wipe',
    entrance: options.motion?.entrance ?? 'left',
    exit: options.motion?.exit ?? 'down',
    staggerFrames: Math.round(options.motion?.staggerFrames ?? packMotion?.staggerFrames ?? 3),
    entranceDurationFrames: Math.round(
      options.motion?.entranceDurationFrames ?? packMotion?.entranceFrames ?? 12,
    ),
    exitDurationFrames: Math.round(
      options.motion?.exitDurationFrames ?? packMotion?.exitFrames ?? 12,
    ),
    entranceEasing: options.motion?.entranceEasing ?? packMotion?.entranceEasing ?? 'cubic-out',
    exitEasing: options.motion?.exitEasing ?? packMotion?.exitEasing ?? 'cubic-in',
  } satisfies ResolvedLowerThirdMotion;
  if (motion.style === 'stagger' && motion.entrance !== 'none') {
    assertStaggerFits(composition, 4, motion.staggerFrames, motion.entranceDurationFrames);
  }

  const panel = recipeLayer(
    composition,
    'rectangle',
    `${name} · Panel`,
    groupId,
    'container',
    ['panel', 'primary'],
    {
      x,
      y,
      width,
      height,
      rotation: 0,
      opacity: 1,
      transformOriginX: 0.5,
      transformOriginY: 0.5,
    },
    motion,
    0,
    motion.style === 'wipe',
  );
  panel.clipChildren = motion.style === 'wipe';
  if (panel.element.type === 'rectangle') {
    panel.element.fill =
      options.theme?.background ?? String(packValue(STYLE_TOKEN_KEYS.surface, '#152235'));
    panel.element.borderRadius = Math.round(height * 0.08);
  }

  const accent = recipeLayer(
    composition,
    'rectangle',
    `${name} · Accent`,
    groupId,
    'accent',
    ['accent'],
    {
      x,
      y,
      width: accentWidth,
      height,
      rotation: 0,
      opacity: 1,
      transformOriginX: 0.5,
      transformOriginY: 0.5,
    },
    motion,
    1,
  );
  if (accent.element.type === 'rectangle') {
    accent.element.fill =
      options.theme?.accent ?? String(packValue(STYLE_TOKEN_KEYS.accent, '#31b7d4'));
    accent.element.borderRadius =
      panel.element.type === 'rectangle' ? panel.element.borderRadius : 0;
  }

  const textX = x + accentWidth + horizontalPadding;
  const textWidth = Math.max(120, width - accentWidth - horizontalPadding * 2);
  const headline = recipeLayer(
    composition,
    'text',
    `${name} · Headline`,
    groupId,
    'headline',
    ['primary', 'editable'],
    {
      x: textX,
      y: y + Math.round(height * 0.16),
      width: textWidth,
      height: Math.round(height * 0.4),
      rotation: 0,
      opacity: 1,
      transformOriginX: 0.5,
      transformOriginY: 0.5,
    },
    motion,
    2,
  );
  if (headline.element.type === 'text') {
    headline.element.content = options.content?.headline ?? 'Headline';
    headline.element.color =
      options.theme?.primaryText ?? String(packValue(STYLE_TOKEN_KEYS.primaryText, '#ffffff'));
    headline.element.fontSize = Math.max(28, Math.round(height * 0.27));
    headline.element.fontWeight = 700;
    headline.element.autoFit = 'shrink-to-fit';
    headline.element.minFontSize = Math.max(18, Math.round(headline.element.fontSize * 0.55));
    headline.element.overflowPolicy = 'clip';
  }

  const subheadline = recipeLayer(
    composition,
    'text',
    `${name} · Subheadline`,
    groupId,
    'subheadline',
    ['secondary', 'editable'],
    {
      x: textX,
      y: y + Math.round(height * 0.57),
      width: textWidth,
      height: Math.round(height * 0.25),
      rotation: 0,
      opacity: 1,
      transformOriginX: 0.5,
      transformOriginY: 0.5,
    },
    motion,
    3,
  );
  if (subheadline.element.type === 'text') {
    subheadline.element.content = options.content?.subheadline ?? 'Secondary line';
    subheadline.element.color =
      options.theme?.secondaryText ?? String(packValue(STYLE_TOKEN_KEYS.secondaryText, '#cbd7e5'));
    subheadline.element.fontSize = Math.max(20, Math.round(height * 0.17));
    subheadline.element.fontWeight = 500;
    subheadline.element.autoFit = 'shrink-to-fit';
    subheadline.element.minFontSize = Math.max(14, Math.round(subheadline.element.fontSize * 0.6));
    subheadline.element.overflowPolicy = 'clip';
  }

  if (motion.style === 'wipe') {
    accent.parentId = panel.id;
    headline.parentId = panel.id;
    subheadline.parentId = panel.id;
  }

  const headlineField = createFieldDefinition('text', {
    key: uniqueFieldKey(composition, options.fieldKeys?.headline ?? 'headline', 'headline'),
    label: `${name} Headline`,
    defaultValue: headline.element.type === 'text' ? headline.element.content : 'Headline',
    description: 'Primary on-air headline.',
    constraints: { maxLength: 80 },
  });
  const reservedFieldKeys = new Set([
    ...composition.dataFields.map((field) => field.key),
    headlineField.key,
  ]);
  let subheadlineKey = uniqueFieldKey(
    composition,
    options.fieldKeys?.subheadline ?? 'subheadline',
    'subheadline',
  );
  if (reservedFieldKeys.has(subheadlineKey)) {
    const base = subheadlineKey;
    let suffix = 2;
    while (reservedFieldKeys.has(`${base}_${suffix}`)) suffix++;
    subheadlineKey = `${base}_${suffix}`;
  }
  const subheadlineField = createFieldDefinition('text', {
    key: subheadlineKey,
    label: `${name} Subheadline`,
    defaultValue:
      subheadline.element.type === 'text' ? subheadline.element.content : 'Secondary line',
    description: 'Secondary on-air context line.',
    constraints: { maxLength: 120 },
  });
  headline.bindings = [{ fieldId: headlineField.id, targetProperty: 'content' }];
  subheadline.bindings = [{ fieldId: subheadlineField.id, targetProperty: 'content' }];

  composition.layers.push(panel, accent, headline, subheadline);
  composition.dataFields.push(headlineField, subheadlineField);
  composition.layout.timelineFolders.push({
    id: timelineGroupId,
    name,
    color:
      typeof (options.theme?.accent ?? '#31b7d4') === 'string'
        ? String(options.theme?.accent ?? '#31b7d4')
        : '#31b7d4',
    layerIds: [panel.id, accent.id, headline.id, subheadline.id],
  });
  if (stylePack) {
    applyStylePack(composition, stylePack, {
      bindLayerIds: [panel.id, accent.id, headline.id, subheadline.id],
      refreshTokens: false,
    });
    const clearBinding = (layer: Layer, property: string) => {
      layer.designTokenBindings = layer.designTokenBindings.filter(
        (binding) => binding.targetProperty !== property,
      );
    };
    if (options.theme?.background !== undefined && panel.element.type === 'rectangle') {
      panel.element.fill = options.theme.background;
      clearBinding(panel, 'fill');
    }
    if (options.theme?.accent !== undefined && accent.element.type === 'rectangle') {
      accent.element.fill = options.theme.accent;
      clearBinding(accent, 'fill');
    }
    if (options.theme?.primaryText !== undefined && headline.element.type === 'text') {
      headline.element.color = options.theme.primaryText;
      clearBinding(headline, 'color');
    }
    if (options.theme?.secondaryText !== undefined && subheadline.element.type === 'text') {
      subheadline.element.color = options.theme.secondaryText;
      clearBinding(subheadline, 'color');
    }
  }

  return {
    recipe: 'lower-third',
    name,
    ...(stylePack ? { stylePack } : {}),
    groupId,
    timelineGroupId,
    layers: {
      panel: panel.id,
      accent: accent.id,
      headline: headline.id,
      subheadline: subheadline.id,
    },
    fields: { headline: headlineField.id, subheadline: subheadlineField.id },
  };
}
