import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { format, resolveConfig } from 'prettier';
import { createOGrafAuthoringHost } from '../apps/mcp-server/src/index';
import { createOGrafMcpServer } from '../apps/mcp-server/src/mcpServer';

const CONTRACT_VERSION = 1;

function markdownFor(tools: Awaited<ReturnType<Client['listTools']>>['tools']): string {
  const rows = tools.map((tool) => {
    const properties = Object.keys(
      (tool.inputSchema as { properties?: Record<string, unknown> }).properties ?? {},
    );
    const access = tool.annotations?.readOnlyHint ? 'read-only' : 'mutation';
    return `| \`${tool.name}\` | ${tool.title ?? ''} | ${access} | ${properties.map((name) => `\`${name}\``).join(', ')} |`;
  });
  return [
    '# Generated MCP contracts',
    '',
    '> Generated by `npm run contracts:generate`. Do not edit this file or the adjacent JSON by hand.',
    '',
    `Contract version: ${CONTRACT_VERSION}`,
    '',
    `Registered tools: ${tools.length}`,
    '',
    'The exact JSON Schema for every registered tool is in [mcp-contracts.json](./mcp-contracts.json). The schemas are generated from the same Zod definitions registered with the MCP SDK, so documentation drift fails `npm run verify`.',
    '',
    '| Tool | Title | Access | Inputs |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

async function generatedFiles() {
  const host = createOGrafAuthoringHost();
  const server = createOGrafMcpServer(host.workspace, host.bridge);
  const client = new Client({ name: 'ograf-contract-generator', version: '1.0.0' });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  try {
    const listed = await client.listTools();
    const contract = {
      contractVersion: CONTRACT_VERSION,
      server: { name: 'ograf-editor', version: '0.1.0' },
      tools: listed.tools,
    };
    const jsonPath = resolve(process.cwd(), 'docs/generated/mcp-contracts.json');
    const markdownPath = resolve(process.cwd(), 'docs/generated/mcp-contracts.md');
    const prettierConfig = (await resolveConfig(jsonPath)) ?? {};
    const [json, markdown] = await Promise.all([
      format(JSON.stringify(contract), { ...prettierConfig, filepath: jsonPath }),
      format(markdownFor(listed.tools), { ...prettierConfig, filepath: markdownPath }),
    ]);
    return {
      json,
      markdown,
    };
  } finally {
    await client.close();
    await server.close();
  }
}

async function main() {
  const files = await generatedFiles();
  const outputDirectory = resolve(process.cwd(), 'docs/generated');
  const targets = [
    { path: resolve(outputDirectory, 'mcp-contracts.json'), content: files.json },
    { path: resolve(outputDirectory, 'mcp-contracts.md'), content: files.markdown },
  ];
  if (process.argv.includes('--check')) {
    const stale: string[] = [];
    for (const target of targets) {
      const current = await readFile(target.path, 'utf8').catch(() => null);
      if (current !== target.content) stale.push(target.path);
    }
    if (stale.length > 0) {
      throw new Error(
        `Generated MCP contracts are stale: ${stale.join(', ')}. Run npm run contracts:generate.`,
      );
    }
    return;
  }
  await mkdir(outputDirectory, { recursive: true });
  await Promise.all(targets.map((target) => writeFile(target.path, target.content, 'utf8')));
}

await main();
