import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { generateInAppPrompt } from '../packages/agent-tools/src/inAppPromptProjection';

async function generatedFiles() {
  const prompt = await generateInAppPrompt();
  const estimatedTokens = Math.ceil(prompt.length / 4);
  const sourcePath = resolve(process.cwd(), 'packages/agent-tools/src/generatedInAppPrompt.ts');
  const prettierConfig = (await resolveConfig(sourcePath)) ?? {};
  const source = await format(
    [
      '// Generated by npm run prompt:generate. Do not edit by hand.',
      `export const IN_APP_SYSTEM_PROMPT = ${JSON.stringify(prompt)};`,
      `export const IN_APP_SYSTEM_PROMPT_BYTES = ${Buffer.byteLength(prompt, 'utf8')};`,
      `export const IN_APP_SYSTEM_PROMPT_ESTIMATED_TOKENS = ${estimatedTokens};`,
      '',
    ].join('\n'),
    { ...prettierConfig, filepath: sourcePath },
  );
  return { source, estimatedTokens };
}

async function main() {
  const files = await generatedFiles();
  const targets = [
    {
      path: resolve(process.cwd(), 'packages/agent-tools/src/generatedInAppPrompt.ts'),
      content: files.source,
    },
  ];
  if (process.argv.includes('--check')) {
    const stale: string[] = [];
    for (const target of targets) {
      const current = await readFile(target.path, 'utf8').catch(() => null);
      if (current?.replace(/\r\n?/g, '\n') !== target.content.replace(/\r\n?/g, '\n'))
        stale.push(target.path);
    }
    if (stale.length > 0) {
      throw new Error(
        `Generated in-app prompt is stale: ${stale.join(', ')}. Run npm run prompt:generate.`,
      );
    }
    return;
  }
  await mkdir(resolve(process.cwd(), 'docs/generated'), { recursive: true });
  await Promise.all(targets.map((target) => writeFile(target.path, target.content, 'utf8')));
  console.log(`Generated in-app prompt: ~${files.estimatedTokens} tokens.`);
}

if (import.meta.url === new URL(`file://${process.argv[1]?.replace(/\\/g, '/')}`).href) {
  await main();
}
